substitutions:
  _AR_HOST: "us-central1-docker.pkg.dev"
  _AR_REPO: "bundle-api"         # Ensure this Artifact Registry repo exists (create once if needed).
  _IMAGE_NAME: "bundle-api"

steps:
  # 1️⃣ Build container for Cloud Run's AMD64 architecture
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--no-cache",
        "--platform", "linux/amd64",
        "-f", "Dockerfile",
        "-t", "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}",
        "."
      ]

  # 2️⃣ Push the image to Artifact / Container Registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}"
      ]

  # 3️⃣ Deploy the new image to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "image-gen-wip",
        "--image", "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}",
        "--region", "us-central1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--memory", "2Gi",
        "--cpu", "2",
        "--timeout", "300",
        "--max-instances", "10",
        "--set-env-vars",
        "OPENBLAS_CORETYPE=HASWELL,GEMINI_API_KEY=AIzaSyDfi3I7z-YMmrBEy6Ij1fBNGUApOfmDAOo,GEMINI_BG_MODEL=gemini-2.0-flash-image"
      ]

images:
  - "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${COMMIT_SHA}"

options:
  # Fix build.service_account logging bucket issue
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true
