substitutions:
  _AR_HOST: "us-central1-docker.pkg.dev"
  _AR_REPO: "bundle-api"
  _IMAGE_NAME: "bundle-api"
  _TAG: "$BUILD_ID"  # Always available in Cloud Build

steps:
  # 1️⃣ Build container for Cloud Run's AMD64 architecture
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--no-cache",
        "--platform", "linux/amd64",
        "-f", "Dockerfile",
        "-t", "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}",
        "."
      ]

  # 2️⃣ Push the image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}"
      ]

  # 3️⃣ Deploy the new image to Cloud Run (bundle-api)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "bundle-api",
        "--image", "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}",
        "--region", "us-central1",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--memory", "2Gi",
        "--cpu", "2",
        "--timeout", "300",
        "--max-instances", "10",
        "--clear-cloudsql-instances",
        "--set-env-vars", "OPENBLAS_CORETYPE=HASWELL,GEMINI_BG_MODEL=gemini-2.0-flash-image",
        "--set-secrets", "DATABASE_URL=DATABASE_URL:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest"
      ]

images:
  - "${_AR_HOST}/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:${_TAG}"

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  dynamic_substitutions: true